# Generated by Django 4.1.6 on 2023-02-08 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Barisal Division', 'Barisal Division'), ('Chittagong Division', 'Chittagong Division'), ('Dhaka Division', 'Dhaka Division'), ('Mymendingh Division', 'Mymendingh Division'), ('Khulna Division', 'Khulna Division'), ('Rajshahi Division', 'Rajshahi Division'), ('Rangpur Division', 'Rangpur Division'), ('Sylhet Division', 'Sylhet Division')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='pending', max_length=50),
        ),
    ]
