# Generated by Django 4.1.6 on 2023-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('paypal', 'paypal'), ('sslcommerz', 'sslcommerz')], default='cash on delivery', max_length=30),
        ),
    ]
