# Generated by Django 4.1.6 on 2023-09-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_customer_orderplaced_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('paypal', 'paypal'), ('sslcommerz', 'sslcommerz')], max_length=30),
        ),
    ]
