# Generated by Django 4.1.6 on 2024-01-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_predicted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
