# Generated by Django 4.1.6 on 2024-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_predict_predicted_price_alter_predict_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.FloatField()),
                ('rom', models.FloatField()),
                ('predictions', models.FloatField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='predict',
        ),
        migrations.RemoveField(
            model_name='product',
            name='predicted_price',
        ),
    ]
