# Generated by Django 4.1.6 on 2024-01-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_data_delete_predict_remove_product_predicted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricePredictionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField()),
                ('rom', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
