# Generated by Django 4.2 on 2024-03-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_pricepredictioninput_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricePredictionInput',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('SSLcommerz', 'SSLcommerz'), ('Cash on Delivery', 'Cash on Delivery'), ('PayPal', 'Paypal')], default='Cash on Delivery', max_length=30),
        ),
    ]
