# Generated by Django 4.2 on 2024-03-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_pricepredictioninput_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment_method',
        ),
    ]
